//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalReferenceDataEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalReferenceDataEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Retrieved. Adjusting Columns..
        /// </summary>
        internal static string ColumnWidthUpdating {
            get {
                return ResourceManager.GetString("ColumnWidthUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Database_32x32 {
            get {
                object obj = ResourceManager.GetObject("Database_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string DatabaseNameString {
            get {
                return ResourceManager.GetString("DatabaseNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DatabaseR_32x32 {
            get {
                object obj = ResourceManager.GetObject("DatabaseR_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string DataObjectsString {
            get {
                return ResourceManager.GetString("DataObjectsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Retrieve complete....
        /// </summary>
        internal static string Donezo {
            get {
                return ResourceManager.GetString("Donezo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EditConnection {
            get {
                object obj = ResourceManager.GetObject("EditConnection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Grid {
            get {
                object obj = ResourceManager.GetObject("Grid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is here, but we are formatting the grid for your viewing pleasure..
        /// </summary>
        internal static string GridIsFormatting {
            get {
                return ResourceManager.GetString("GridIsFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Tables.
        /// </summary>
        internal static string HideTables {
            get {
                return ResourceManager.GetString("HideTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing application..
        /// </summary>
        internal static string InitializingForm1 {
            get {
                return ResourceManager.GetString("InitializingForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing DataSources..
        /// </summary>
        internal static string IntializingDataSourcesForm1 {
            get {
                return ResourceManager.GetString("IntializingDataSourcesForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Key).
        /// </summary>
        internal static string KeyString {
            get {
                return ResourceManager.GetString("KeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameColumnString {
            get {
                return ResourceManager.GetString("NameColumnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no action specified. Please write some sql that does something. (e.g. select or execute).
        /// </summary>
        internal static string NoActionSelectedString {
            get {
                return ResourceManager.GetString("NoActionSelectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DB selected..
        /// </summary>
        internal static string NoDbSelectedCaption {
            get {
                return ResourceManager.GetString("NoDbSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected to query. Click on a database and re-run the query..
        /// </summary>
        internal static string Nodbselectedstring {
            get {
                return ResourceManager.GetString("Nodbselectedstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOPE.
        /// </summary>
        internal static string Nope {
            get {
                return ResourceManager.GetString("Nope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOPE! JUST NOPE! THIS ISNT THAT KIND OF PLACE. YOU GO RUN A PROPER SQL IDE FOR THAT KINDA BEHAVIOR!!!!.
        /// </summary>
        internal static string NotAllowedToDoThatString {
            get {
                return ResourceManager.GetString("NotAllowedToDoThatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrieve complete, preparing for display..
        /// </summary>
        internal static string PreperatingDataForm1 {
            get {
                return ResourceManager.GetString("PreperatingDataForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Data From Table....
        /// </summary>
        internal static string RetrievingDataNow {
            get {
                return ResourceManager.GetString("RetrievingDataNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Query of {0} returned {1} rows in {2} milliseconds.
        /// </summary>
        internal static string RunReturnedRowsInMilliseconds {
            get {
                return ResourceManager.GetString("RunReturnedRowsInMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tables.
        /// </summary>
        internal static string ShowTables {
            get {
                return ResourceManager.GetString("ShowTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a source for the query. (e.g. FROM).
        /// </summary>
        internal static string ThereNeedsToBeAFromClauseString {
            get {
                return ResourceManager.GetString("ThereNeedsToBeAFromClauseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! The RowCount for {0} is {1}, if you click ok it will select * from this table and could take very long time and cause OOM exceptions, the lights to flicker, etc. Continue???.
        /// </summary>
        internal static string ThisIsAHUGEQuery {
            get {
                return ResourceManager.GetString("ThisIsAHUGEQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating width on column {0}.
        /// </summary>
        internal static string updating_Column {
            get {
                return ResourceManager.GetString("updating Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Data Edit Window Version .
        /// </summary>
        internal static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count warning prompt here.
        /// </summary>
        internal static string WarningPromptHere {
            get {
                return ResourceManager.GetString("WarningPromptHere", resourceCulture);
            }
        }
    }
}
